library(dplyr)
library(ggplot2)
library(readr)
library(xlsx)
Shi05082017_NACC <- read_csv("~/myfolders/data/Shi05082017-NACC.csv")
View(Shi05082017_NACC)
str(Shi05082017_NACC)
# 47673 obs. of  193 variables:


  
Data_Select <- select(Shi05082017_NACC,NACCADC,NACCID, BIRTHYR,SEX,EDUC,INDEPEND,RESIDENC,MARISTAT,HEIGHT,WEIGHT,NACCBMI,BPSYS,
                      BPDIAS,HRATE,VISION,VISCORR,VISWCORR,HEARING,HEARAID,HEARWAID,TOBAC30,TOBAC100,SMOKYRS,PACKSPER,QUITSMOK,ALCOCCAS,ALCFREQ,CVHATT,HATTMULT,
                      CBSTROKE,STROKMUL,SEIZURES,DIABETES,DIABTYPE,HYPERTEN,HYPERCHO,B12DEF,THYROID,ARTHRIT,INSOMN,ALCOHOL,ABUSOTHR,BIPOLAR,SCHIZ,DEP2YRS,DEPOTHR,
                      ANXIETY,NACCAPOE,NACCNE4S,NPTHAL)
View(Data_Select)
write.table(Data_Select, "C:/Users/mingj/Documents/MSDS")